web2019asn_p03_team3/Models/SkillSet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace web2019asn_p03_team3.Models
{
    public class SkillSet
    {
        public int SkillSetID { get; set; }

        public string SkillSetName { get; set; }
    }
}

web2019asn_p03_team3/Controllers/SkillsetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using web2019asn_p03_team3.DAL;
using web2019asn_p03_team3.Models;

namespace web2019asn_p03_team3.Controllers
{
    public class SkillSetController : Controller
    {
        private SkillsetDAL ssContext = new SkillsetDAL();
        private StudentDAL sContext = new StudentDAL();
        private LecturerDAL lContext = new LecturerDAL();

        // GET: SkillSet
        public ActionResult Index()
        {
            if ((HttpContext.Session.GetString("Role") != "Lecturer"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<SkillSet> ssList = ssContext.getAllSkillSets();
            return View(ssList);
        }

        // GET: SkillSet/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
            
        // GET: SkillSet/Create
        public ActionResult Create()
        {
            if (HttpContext.Session.GetString("Role") == null || HttpContext.Session.GetString("Role")  != "Lecturer")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // POST: SkillSet/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SkillSet ss)
        {
            if (ssContext.isSkillSetExists(ss.SkillSetName))
            {
                ss.SkillSetID = ssContext.AddSkillSet(ss);
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["Message"] = "Skillset name already exists!";
                return View();
            }
        }

        public ProjectViewModel MapToSSVM(SkillSet ss)
        {
            ProjectViewModel SSVM = new ProjectViewModel
            {
                ProjectID = ss.SkillSetID,
                ProjectTitle = ss.SkillSetName
            };

            return SSVM;
        }

        // GET: SkillSet/Edit/5
        public ActionResult Edit(int? id)
        {

            SkillSet ss = ssContext.GetSkillSetDetails(id.Value);
            if (ss == null)
            {
                return RedirectToAction("Index");
            }

            HttpContext.Session.SetString("SkillSetID", id.Value.ToString());

            return View(ss);
        }

        // POST: SkillSet/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SkillSet ss)
        {
            ss.SkillSetID = Convert.ToInt32(HttpContext.Session.GetString("SkillSetID"));
            ssContext.Update(ss);
            return RedirectToAction("Index");
        }

        // GET: SkillSet/Delete/5
        public ActionResult Delete(int? id)
        {
            SkillSet ss = ssContext.GetSkillSetDetails(id.Value);

            if (ss == null)
            {
                return RedirectToAction("Index");
            }

            HttpContext.Session.SetString("SkillSetID", id.Value.ToString());
            return View();
        }

        // POST: SkillSet/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(SkillSet ss)
        {
            ss.SkillSetID = Convert.ToInt32(HttpContext.Session.GetString("SkillSetID"));
            if (ssContext.isStudentSkillSetExists(ss.SkillSetID))
            {
                ssContext.Delete(ss.SkillSetID);
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["Message"] = "Skillset is assigned to some students!";
                return View();
            }
        }

        public List<Student> GetStudents(int id)
        {
            List<int> studentID = ssContext.GetStudentID(id);
            List<Student> studentSkillSet = new List<Student>();

            foreach(int s in studentID)
            {
                studentSkillSet.Add(sContext.GetStudentProfile(s));
            }
            return studentSkillSet;
        }

        public ActionResult ViewStudent(int id)
        {
            SkillSet ss = ssContext.GetDetails(id);
            List<Student> studentList = GetStudents(id);
            StudentSkillSet studentSkillSet = new StudentSkillSet { SkillSet = ss, Students = studentList };
            return View(studentSkillSet);
        }

        public ActionResult ViewProfile(int id)
        {
            MenteeViewModel m = new MenteeViewModel { skillset = lContext.GetSkillSets(id), student = lContext.GetMentee(id) };
            return View(m);
        }
    }
}

web2019asn_p03_team3/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using web2019asn_p03_team3.DAL;
using web2019asn_p03_team3.Models;

namespace web2019asn_p03_team3.Controllers
{
    public class StudentController : Controller
    {
        private StudentDAL studentContext = new StudentDAL();
        private SkillsetDAL skillsetContext = new SkillsetDAL();
        public IActionResult Index()
        {
            List<Student> studentList = studentContext.GetAllStudent();
            return View(studentList);
        }

        public ActionResult acknowledge (int sId)
        {
            int studentId = Convert.ToInt32(HttpContext.Session.GetString("StudentID"));
            studentContext.Acknowledge(sId, studentId);
            TempData["acknowledge"] = "you have acknowledge";
            return RedirectToAction("Studentsuggestion", new { id =  studentId });
        }

        // suggestion student 
        private List<Suggestion> GetSuggestionslist(int id)
        {
        
            List<Suggestion> suggestionslist = studentContext.GetStudentSuggestions(id);
            return suggestionslist;
        }
        public ActionResult Studentsuggestion(int id)
        {
            
            Student student = studentContext.GetStudentProfile(id);
            StudentViewModel studentvm = MapToStudentVM(student);
            ViewData["Acknowledge"] = TempData["acknowledge"];
            return View(studentvm);
        }
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Studentsuggestion()
        //{
        //    if (ModelState.IsValid)
        //    {
        //        ViewData["message"] = "you have acknowledge!!";
        //    }
        //    return RedirectToAction("Index");
        //}


        // GET: Student/Edit
        // when user see the edit.cshtml 

        public ActionResult Edit(int? id)
        {
            if (id == null) //Query string parameter not provided
            {
                return RedirectToAction("Index");
            }

            Student student = studentContext.GetStudentProfile(id.Value);
            if (student == null)
            {
                return RedirectToAction("Index");
            }
            TempData["msg"] = "Please fill in the boxes";

            return View(MapToStudentVM(student));


        }

        //when user clicks on the save in edit.cshtml
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Student student)
        {
            studentContext.Update(student);
            return RedirectToAction("Index");
           
        }
        
        private List<SelectListItem> GetSkillLists()
        {
            List<SelectListItem> skills = new List<SelectListItem>();
            skills.Add(
            new SelectListItem
            {
                Value = "",
                Text = "--Select--"
            });
            List<SkillSet> skilllist = skillsetContext.getAllSkillSets();
            foreach (SkillSet skill in skilllist)
            {
                skills.Add(
                new SelectListItem
                {
                    Value = skill.SkillSetID.ToString(),
                    Text = skill.SkillSetName
                });
            }
            return skills;
        }
        private List<SelectListItem> GetLecturerLists()
        {
            List<SelectListItem> lecturers = new List<SelectListItem>();
            lecturers.Add(
            new SelectListItem
            {
                Value = "",
                Text = "--Select--"
            });
            List<Lecturer> lecturerlist = studentContext.getstudentlecturer();
            foreach (Lecturer lect in lecturerlist)
            {
                lecturers.Add(
                new SelectListItem
                {
                    Value = lect.LecturerID.ToString(),
                    Text = lect.LecturerName
                });
            }
            return lecturers;
        }

        public ActionResult StudentSkill(int id)
        {
            ViewData["Skilllist"] = GetSkillLists();
            Student student = studentContext.GetStudentProfile(id);
            StudentViewModel studentvm = MapToStudentVM(student);
            return View(studentvm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult StudentSkill(StudentViewModel student)
        {
            ViewData["Skilllist"] = GetSkillLists();
            //student.StudentID = Convert.ToInt32(HttpContext.Session.GetString("StudentID"));
            if (ModelState.IsValid)
            {
                //Update staff record to database
                studentContext.updateskills(student);
                return RedirectToAction("Index");
            }
            //Input validation fails, return to the view
            //to display error message
            return View((student));
            //studentContext.Update(student);
            //return RedirectToAction("Index");
        }


            public ActionResult Studentphoto(int id)
        {
            Student student = studentContext.GetStudentProfile(id);
            StudentViewModel studentvm = MapToStudentVM(student);
            return View(studentvm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Studentphoto(StudentViewModel studentvm)
        {
            if (studentvm.FileToUpload != null && studentvm.FileToUpload.Length > 0)
            {
                try
                {
                    // Find the filename extension of the file to be uploaded.
                    string fileExt = Path.GetExtension(studentvm.FileToUpload.FileName);

                    // Rename the uploaded file with the staff’s name.
                    string uploadedFile = studentvm.StudentID + fileExt;

                    // Get the complete path to the images folder in server
                    string savePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", uploadedFile);

                    // Upload the file to server
                    using (var fileSteam = new FileStream(savePath, FileMode.Create))
                    {
                        await studentvm.FileToUpload.CopyToAsync(fileSteam);
                    }
                    studentvm.StudentPhoto = uploadedFile;
                    studentContext.Upload(uploadedFile, studentvm.StudentID);
                    ViewData["Message"] = "File uploaded successfully.";
                }
                catch (IOException)
                {
                    //File IO error, could be due to access rights denied
                    ViewData["Message"] = "File uploading fail!";
                }
                catch (Exception ex) //Other type of error
                {
                    ViewData["Message"] = ex.Message;
                }
            }
            return View(studentvm);
        }

        

        // GET: Student/Profile 
        public ActionResult Profile(int id)
        {
            Student student = studentContext.GetStudentProfile(id);
            StudentViewModel StudentVM = MapToStudentVM(student);

            return View(StudentVM);
        }
        public StudentViewModel MapToStudentVM(Student student)
        {
            List<SkillSet> studentskillAlllist = skillsetContext.getAllSkillSets();
            List<Suggestion> suggestionslist = studentContext.GetStudentSuggestions(student.StudentID);

            StudentViewModel StudentVM = new StudentViewModel
            {
                StudentID = student.StudentID,
                StudentDescription = student.StudentDescription,
                StudentName = student.StudentName,
                StudentPhoto = student.StudentPhoto,
                StudentLink = student.StudentLink,
                StudentAchievement = student.StudentAchievement,
                StudentEmailAddr = student.StudentEmailAddr,
                MentorID = student.MentorID.ToString(),
                StudentCourse = student.StudentCourse,
                AllSkillSets = studentskillAlllist,
                Studentskills = skillsetContext.GetskillsetStudent(student.StudentID),
                StudentSuggestions = suggestionslist

            };

            return StudentVM;
        }




    }
}

web2019asn_p03_team3/Views/Skillset/Create.cshtml
@model web2019asn_p03_team3.Models.SkillSet

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Create</h2>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="SkillSetName" class="control-label"></label>
                    <input asp-for="SkillSetName" class="form-control" />
                    <span asp-validation-for="SkillSetName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </form>

            <span class="text-dagger" style="color:red">@ViewData["Message"]</span>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

</div>

web2019asn_p03_team3/Views/Skillset/Delete.cshtml
@model web2019asn_p03_team3.Models.SkillSet

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <hr />
        <div>
            <form asp-action="Delete">
                <input type="submit" value="Yes" class="btn btn-default col-md-1" />
            </form>

            <span class="text-dagger" style="color: red">@ViewData["Message"]</span>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </div>
</div>

web2019asn_p03_team3/Views/Skillset/Edit.cshtml
@model web2019asn_p03_team3.Models.SkillSet

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="">
    <div class="container">
        <h2>Edit</h2>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="SkillSetName" class="control-label"></label>
                        <input asp-for="SkillSetName" class="form-control" />
                        <span asp-validation-for="SkillSetName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </div>
</div>

web2019asn_p03_team3/Views/Skillset/Index.cshtml
@model IEnumerable<web2019asn_p03_team3.Models.SkillSet>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="py-5">
    <div class="container">
        @if (Context.Session.GetString("Role") != null)
        {
            if (Context.Session.GetString("Role") == "Lecturer")
            {
                <div class="container d-flex">
                    <h3>List of Skill Sets</h3>
                </div>
                <hr />
                @await Html.PartialAsync("_ViewSkillSets.cshtml")
            }
        }
    </div>
</div>

web2019asn_p03_team3/Views/Skillset/ViewStudent.cshtml
@model web2019asn_p03_team3.Models.StudentSkillSet

@{
    ViewData["Title"] = "ViewStudent";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="">
    <div class="container">
        <div class="container d-flex">
            <h3>List of Students</h3>
        </div>
        <hr />

        @if (@Model.Students.Count() > 0)
        {
            <div class="table-responsive">
                <table id="viewSkillSets" class="table table-striped table-bordered">
                    <thead class="thead-dark">
                        <tr>
                            <th>StudentID</th>
                            <th>StudentName</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var s in @Model.Students)
                        {
                            <tr>
                                <td>@s.StudentID.ToString()</td>
                                <td>@s.StudentName</td>
                                <td>
                                    <a asp-action="Profile" asp-controller="Student" asp-route-id="@s.StudentID">View Profile</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
        else
        {
            <span style="color:red">No record found!</span>
        }
        <div>
            <br /><a asp-action="Index" asp-controller="SkillSet">Return to List of Skillsets</a>
        </div>
    </div>
</div>

web2019asn_p03_team3/Views/Skillset/_ViewSkillSets.cshtml
@model IEnumerable<web2019asn_p03_team3.Models.SkillSet>


<div class="">
    <div class="container">
        <p>
            <a asp-action="Create">Create New</a>
        </p>
        <div class="table-responsive">
            <table id="viewSkillSets" class="table table-striped table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.SkillSetID)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SkillSetName)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var ss in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => ss.SkillSetID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => ss.SkillSetName)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-controller="SkillSet" asp-route-id="@ss.SkillSetID"><p>Edit</p></a>
                                <a asp-action="Delete" asp-controller="SkillSet" asp-route-id="@ss.SkillSetID"><p>Delete</p></a>
                                <a asp-action="ViewStudent" asp-controller="SkillSet" asp-route-id="@ss.SkillSetID"><p>View Students</p></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>