web2019asn_p03_team3/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace web2019asn_p03_team3.Models
{
    public class Project
    {
        //auto generated and is required, find a way to auto generate
        public int ProjectID { get; set; }

        [Display(Name = "Project Title")]
        [Required(ErrorMessage ="You must enter a project title")]
        [StringLength(255, ErrorMessage = "Maximum number of characters must be 255")]
        public string ProjectTitle { get; set; }

        [Display(Name = "Project Description")]
        [StringLength(3000, ErrorMessage = "Maximum number of characters must be 3000")]
        public string ProjectDescription { get; set; }

        [Display(Name = "Project Poster")]
        [StringLength(255, ErrorMessage = "Maximum number of characters must be 255")]
        public string ProjectPoster { get; set; }

        [Display(Name = "Project Url")]
        [StringLength(255, ErrorMessage = "Maximum number of characters must be 255")]
        public string ProjectURL { get; set; }


    }
}

web2019asn_p03_team3/Models/ProjectViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace web2019asn_p03_team3.Models
{
    public class ProjectViewModel
    {
        public int ProjectID { get; set; }

        [Display(Name = "Project Title")]
        public string ProjectTitle { get; set; }

        [Display(Name = "Project Description")]
        public string ProjectDescription { get; set; }

        [Display(Name = "Project Poster")]
        public string ProjectPoster { get; set; }

        [Display(Name = "Project Url")]
        public string ProjectURL { get; set; }

        public IFormFile FileToUpload { get; set; }

        public List<Student> Members { get; set; }

        public Student Leader { get; set; }
    }
}

web2019asn_p03_team3/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using web2019asn_p03_team3.DAL;
using web2019asn_p03_team3.Models;

namespace web2019asn_p03_team3.Controllers
{
    public class ProjectController : Controller
    {
        private ProjectDAL projectContext = new ProjectDAL();
        private StudentDAL studentContext = new StudentDAL();
        // GET: Project
        public ActionResult Index()
        {
            if (HttpContext.Session.GetString("Role") == "Student")
            {
                var studentId = HttpContext.Session.GetString("StudentID");
                List<Project> projectbyStudentList = projectContext.getProjectByStudent(Convert.ToInt32(studentId));
                return View(projectbyStudentList);
            }
            else
            {
                List<Project> projectList = projectContext.getAllProjects();
                return View(projectList);
            }

            
        }

        // GET: Project/Details/5
        public ActionResult Details(int id)
        {
            Project project = projectContext.GetProjectDetails(id);
            ProjectViewModel ProjVM = MapToProjVM(project);
            //if (ProjVM.Members.Count > 1)
            //{
            //    ProjVM.Members.Clear();
            //}
            ProjVM.Members = new List<Student>();
            ProjVM.Members = projectContext.getMembers(id);
            ProjVM.Leader = projectContext.getLeader(id);
            return View(ProjVM);
        }

        public ProjectViewModel MapToProjVM(Project project)
        {

            ProjectViewModel ProjVM = new ProjectViewModel
            {
                ProjectID = project.ProjectID,
                ProjectDescription = project.ProjectDescription,
                ProjectTitle = project.ProjectTitle,
                ProjectPoster = project.ProjectPoster,
                ProjectURL = project.ProjectURL,

            };

            return ProjVM;
        }

        // GET: Project/Create
        public ActionResult Create()
        {
            return View();
        }


        // POST: Project/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Project project)
        {
            if (ModelState.IsValid)
            {
                var studentId = HttpContext.Session.GetString("StudentID");
                project.ProjectID = projectContext.AddProject(project, Convert.ToInt32(studentId));
                return RedirectToAction("Index");
            }
            else
            {
                return View(project);
            }
        }

        // GET: Project/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null) //Query string parameter not provided
            {
                return RedirectToAction("Index");
            }

            Project project = projectContext.GetProjectDetails(id.Value);
            if (project == null)
            {
                return RedirectToAction("Index");
            }
            return View(project);
        }

        // POST: Project/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Project project)
        {
            if (ModelState.IsValid)
            {
                projectContext.Update(project);
                return RedirectToAction("Index");
            }

            //Input validation fails, return to the view
            //to display error message
            return View(project);
        }

        // GET: Project/Delete/5
        public ActionResult Delete(int? id)
        {

            //IN THIS METHOD THE ID IS SHOWN
            

            Project project = projectContext.GetProjectDetails(id.Value);
            
            if (project == null)
            {
                return RedirectToAction("Index");
            }

            HttpContext.Session.SetString("ProjectID", id.Value.ToString());

            return View(project);
        }

        // POST: Project/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Project project)
        {
            // IN THIS METHOD EVERYTHING IS NULL
            // So i will use session cookie
            project.ProjectID = Convert.ToInt32(HttpContext.Session.GetString("ProjectID"));
            projectContext.Delete(project.ProjectID);
            return RedirectToAction("Index");
        }

        public ActionResult UploadPhoto(int id)
        {
            Project project = projectContext.GetProjectDetails(id);
            ProjectViewModel projVM = MapToProjVM(project);
            return View(projVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadPhoto(ProjectViewModel projVM)
        {
            if (projVM.FileToUpload != null && projVM.FileToUpload.Length > 0)
            {
                try
                {
                    // Find the filename extension of the file to be uploaded.
                    string fileExt = Path.GetExtension(projVM.FileToUpload.FileName);

                    // Rename the uploaded file with the staff’s name.
                    string uploadedFile = projVM.ProjectTitle + fileExt;

                    // Get the complete path to the images folder in server
                    string savePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", uploadedFile);

                    // Upload the file to server
                    using (var fileSteam = new FileStream(savePath, FileMode.Create))
                    {
                        await projVM.FileToUpload.CopyToAsync(fileSteam);
                    }

                    //projVM.FileToUpload

                    projVM.ProjectPoster = uploadedFile;
                    projectContext.Upload(uploadedFile, projVM.ProjectID);
                    ViewData["Message"] = "File uploaded successfully.";
                }
                catch (IOException)
                {
                    //File IO error, could be due to access rights denied
                    ViewData["Message"] = "File uploading fail!";
                }
                catch (Exception ex) //Other type of error
                {
                    ViewData["Message"] = ex.Message;
                }
            }
            return View(projVM);
        }

        private List<SelectListItem> GetAllStudents(int id)
        {
            List<SelectListItem> students = new List<SelectListItem>();

            List<Student> studentList = studentContext.GetAllStudent();
            Student leader = projectContext.getLeader(id);

            //students.Add(
            //    new SelectListItem
            //    {
            //        Value = leader.StudentID.ToString() + "Leader",
            //        Text = leader.StudentName,
            //        Disabled = true
            //    });

            foreach (Student s in studentList)
            {
                students.Add(
                new SelectListItem
                {
                    Value = s.StudentID.ToString(),
                    Text = s.StudentName
                });
            }

            for (int i = 0; i < students.Count; i++)
            {
                for (int x = 0; x < GetAllMembers(id).Count; x++)
                {
                    if (students[i].Value == GetAllMembers(id)[x].Value)
                    {
                        students[i].Disabled = true;
                    }
                    if (students[i].Value == leader.StudentID.ToString())
                    {
                        students[i].Text = leader.StudentName + " - Leader";
                        students[i].Disabled = true;
                    }
                }
            }

            return students;
        }

        public ActionResult AddnRemoveMembers(int id)
        {
            Project project = projectContext.GetProjectDetails(id);
            ProjectViewModel projVM = MapToProjVM(project);
            ViewData["studentList"] = GetAllStudents(id);
            projVM.Members = new List<Student>();
            return View(projVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddnRemoveMembers(IFormCollection ifc, int id, ProjectViewModel projVm)
        {
            var members = ifc["Members"];

            

            foreach (var item in members)
            {
                var student = studentContext.GetStudentProfile(Convert.ToInt32(item));
                projectContext.addMembers(student.StudentID,id);
                
            }
            
            ViewData["studentList"] = GetAllStudents(id);

            return RedirectToAction("Details",new { id = id });
        }
        
        private List<SelectListItem> GetAllMembers(int id)
        {
            List<SelectListItem> members = new List<SelectListItem>();
            Student leader = projectContext.getLeader(id);
            members.Add(
               new SelectListItem
               {
                   Value = leader.StudentID.ToString(),
                   Text = leader.StudentName += " - Leader",
                   Disabled = true
               });

            List<Student> memberList = projectContext.getMembers(id);
            foreach (Student s in memberList)
            {
                members.Add(
                new SelectListItem
                {
                    Value = s.StudentID.ToString(),
                    Text = s.StudentName
                });
            }

            return members;
        }

        public ActionResult RemoveMembers(int id)
        {
            ViewData["memberList"] = GetAllMembers(id);
            Project project = projectContext.GetProjectDetails(id);

web2019asn_p03_team3/Views/Project/AddnRemoveMembers.cshtml
@model web2019asn_p03_team3.Models.ProjectViewModel

@{
    ViewData["Title"] = "AddnRemoveMembers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<hr />
<h2>Add Members</h2>
<div class="row">
    <div class="col-md-6">
        <form asp-action="AddnRemoveMembers">
            <div class="form-group row">
                <label asp-for="Members" class="col-sm-3 col-form-label">Add Members</label>
                <div class="col-sm-9 col-md-5">
                    <select asp-for="Members" asp-items="@ViewData["studentList"] as List<SelectListItem>" class="form-control selectFunc" multiple></select>
                </div>
            </div>

            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </form>
    </div>
    
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

   

web2019asn_p03_team3/Views/Project/Create.cshtml
@model web2019asn_p03_team3.Models.Project

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="py-5  text-center">
    <div class="container">
        <div class="row">
            <div class="mx-auto p-4 col-md-7">
                <h1 class="mb-4">Add a project</h1>
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <input asp-for="ProjectTitle" type="text" class="form-control" placeholder="Title">
                        <span asp-validation-for="ProjectTitle" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input asp-for="ProjectURL" type="text" class="form-control" placeholder="URL to project">
                        <span asp-validation-for="ProjectURL" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <textarea asp-for="ProjectDescription" class="form-control" rows="3" placeholder="Description"></textarea>
                        <span asp-validation-for="ProjectDescription" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input asp-for="ProjectPoster" class="form-control" rows="3" placeholder="Upload Photo - yet to be completed">
                        <span asp-validation-for="ProjectPoster" class="text-danger"></span>
                    </div>
                    <button type="submit" value="Create" class="btn btn-outline-primary btn-block">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

web2019asn_p03_team3/Views/Project/Delete.cshtml
@model web2019asn_p03_team3.Models.Project

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <h4>Project</h4>
    <h3>Are you sure you want to delete this?</h3>
    <hr />
    <div class="form-group row">
        <label asp-for="ProjectID" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 col-md-5">
            <input asp-for="ProjectID" readonly class="form-control-plaintext" />
        </div>
    </div>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

web2019asn_p03_team3/Views/Project/Details.cshtml
@model web2019asn_p03_team3.Models.ProjectViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="px-md-5 px-sm-1">
    <div class="container-fluid">
        <div class="row">
            <div class="p-sm-1 col-lg-6 d-flex">
                <img class="d-block img-fluid mx-auto" style="width:auto;" src="~/images/@Model.ProjectPoster">
            </div>
            <div class="p-sm-1 p-md-5 col-lg-6">

                <h1 class="text-center mt-5">@Model.ProjectTitle</h1>
                <small class="mt-5">Project ID : @Model.ProjectID</small>

                <div class="py-2">
                    <h2 class="mt-5">Project Description</h2>
                    <p class="mt-2">@Model.ProjectDescription</p>
                </div>

                <div class="pt-1 pb-5">
                    <h3 class="mt-5">URL to project</h3>
                    <a href="@Model.ProjectURL" class="mt-2 ">@Model.ProjectURL</a>
                </div>
                
                <div class="py-2">
                    <h3>Members</h3>
                    <p>@Model.Leader.StudentName.ToString() - <b>Leader</b></p>
                    @foreach (var item in Model.Members)
                    {
                        <p>@item.StudentName - Member</p>
                    }
                </div>
            </div>
        </div>
        
    </div>
</div>

web2019asn_p03_team3/Views/Project/Edit.cshtml
@model web2019asn_p03_team3.Models.Project

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="py-5  text-center">
<div class="container">
    <div class="row">
        <div class="mx-auto p-4 col-md-7">
            <h1 class="mb-4">Edit Project</h1>
            <form asp-action="Edit" class="text-left">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="ProjectID" class="control-label font-weight-bold"></label>
                    <input asp-for="ProjectID" readonly class="form-control" />
                    <span asp-validation-for="ProjectID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProjectTitle" class="control-label font-weight-bold"></label>
                    <input asp-for="ProjectTitle" class="form-control" />
                    <span asp-validation-for="ProjectTitle" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProjectDescription" class="control-label font-weight-bold"></label>
                    <textarea asp-for="ProjectDescription" class="form-control" rows="3" placeholder="Description"></textarea>
                    <span asp-validation-for="ProjectDescription" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProjectPoster" class="control-label font-weight-bold"></label>
                    <div class="d-flex">
                        <input asp-for="ProjectPoster" class="form-control" readonly />
                        <a asp-action="UploadPhoto" asp-route-id="@Model.ProjectID" class="btn btn-secondary">Upload Photo</a>
                    </div>
                    <span asp-validation-for="ProjectPoster" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProjectURL" class="control-label font-weight-bold"></label>
                    <input asp-for="ProjectURL" class="form-control" />
                    <span asp-validation-for="ProjectURL" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label><b>Members</b></label>
                    <div class="d-flex">
                        <a asp-action="AddnRemoveMembers" asp-route-id="@Model.ProjectID" class="btn btn-primary mr-1">Add</a>
                        <a asp-action="RemoveMembers" asp-route-id="@Model.ProjectID" class="btn btn-danger mx-1">Remove</a>
                    </div>
                </div>

                <div class="form-group mt-5">
                    <input type="submit" value="Save" class="btn btn-warning" />
                </div>
</form>
        </div>
    </div>
</div>
</div>

web2019asn_p03_team3/Views/Project/Index.cshtml
@model IEnumerable<web2019asn_p03_team3.Models.Project>

@{
    ViewData["Title"] = "Projects";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="py-5">
    <div class="container">
        @if (Context.Session.GetString("Role") != null)
        {
            if (Context.Session.GetString("Role") == "Student")
            {
                <h2>My Projects</h2>
            }
        }
        else
        {
            <h2>All Projects</h2>
        }
        <div class="row">
            <div class="col-md-12">
                <hr />
                @*<a class="text-dark" asp-action="Create" style="text-decoration:none;"><i class="fas fa-plus d-inline mr-1"></i></a>
                <a class="text-dark" asp-action="Create" style="text-decoration:none;"><p class="d-inline">Create a new Project</p></a>*@
                @{
                    @if (Context.Session.GetString("Role") != null)
                    {
                        if (Context.Session.GetString("Role") == "Student")
                        {
                            <a class="text-dark" asp-action="Create" style="text-decoration:none;"><i class="fas fa-plus d-inline mr-1"></i></a>
                            <a class="text-dark" asp-action="Create" style="text-decoration:none;"><p class="d-inline">Create a new Project</p></a>
                            @await Html.PartialAsync("_ViewProjects.cshtml")
                        }
                    }
                    else
                    {
                        @await Html.PartialAsync("_ViewProjects.cshtml")
                    }
                }
                @*<partial name="~/Views/Staff/_ViewStaff.cshtml" model="@Model" />*@
            </div>
        </div>
    </div>
</div>

web2019asn_p03_team3/Views/Project/RemoveMembers.cshtml
@model web2019asn_p03_team3.Models.ProjectViewModel

@{
    ViewData["Title"] = "RemoveMembers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Remove Members</h2>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="RemoveMembers">
            <div class="form-group row">
                <label asp-for="Members" class="col-sm-3 col-form-label">Remove Members</label>
                <div class="col-sm-9 col-md-5">
                    <select asp-for="Members" asp-items="@ViewData["memberList"] as List<SelectListItem>" class="form-control selectFunc" multiple></select>
                </div>
            </div>

            <div class="form-group">
                <input type="submit" value="Remove" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

web2019asn_p03_team3/Views/Project/UploadPhoto.cshtml
@model web2019asn_p03_team3.Models.ProjectViewModel

@{
    ViewData["Title"] = "UploadPhoto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>UploadPhoto</h2>

<h4>ProjectViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UploadPhoto" enctype="multipart/form-data">
            <div class="form-group row">
                <label asp-for="ProjectID"
                       class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9 col-md-5">
                    <input asp-for="ProjectID" readonly
                           class="form-control-plaintext" />
                </div>
            </div>

            <div class="form-group row">
                <label asp-for="ProjectTitle" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9 col-md-5">
                    <input asp-for="ProjectTitle" readonly class="form-control-plaintext" />
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="ProjectPoster"
                       class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <img src="~/images/@Model.ProjectPoster" style="height:20vh;width:auto;"/>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="FileToUpload"
                       class="col-sm-3 col-form-label">
                    New Photo (jpg format)
                </label>
                <div class="col-sm-9">
                    <input asp-for="FileToUpload" accept="image/jpeg" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-9 offset-sm-3">
                    <input type="submit" value="Upload"
                           class="btn btn-primary" />
                    <span style="color:red;">@ViewData["Message"]</span>
                </div>
            </div>


        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

web2019asn_p03_team3/Views/Project/_ViewProjects.cshtml
@model IEnumerable<web2019asn_p03_team3.Models.Project>

<div class="py-5">
    <div class="container">
        <div class="row">
            @try
            {
                @if (Model.ToList().Count > 0)
                {
                    foreach (var project in Model)
                    {

                        <div class="col-md-3 col-sm-6">
                            <div class="card mt-4">
                                <div class="zoomProj">
                                    <a asp-action="Details" asp-controller="Project" asp-route-id="@project.ProjectID"><img class="card-img-top" src="~/images/@project.ProjectPoster" alt="Card image cap"></a>
                                </div>
                                <div class="card-body">
                                    @if (Context.Session.GetString("Role") == "Student")
                                    {
                                        <div class="text-right">
                                            <a asp-action="Details" asp-controller="Project" asp-route-id="@project.ProjectID"> <i class="fas fa-eye"></i></a>
                                            <a asp-action="Edit" asp-controller="Project" asp-route-id="@project.ProjectID"><i class="fas fa-edit"></i></a>
                                            <a asp-action="Delete" asp-controller="Project" asp-route-id="@project.ProjectID"><i class="fas fa-trash-alt"></i></a>
                                        </div>
                                    }

                                    <small>Project ID : @project.ProjectID</small>
                                    <h5 class="card-title">@project.ProjectTitle</h5>
                                    @if (Context.Session.GetString("Role") != "Student")
                                    {
                                        <a asp-action="Details" asp-controller="Project" asp-route-id="@project.ProjectID" class="btn btn-primary">View Project</a>
                                    }
                                </div>
                            </div>
                        </div>

                    }
                }
                else
                {
                    <div class="container">
                        <div class="text-center">
                            <h1 class="display-1" style="color:red">No Projects Found</h1>
                        </div>
                    </div>
                }
            }
            catch
            {

                <div class="container">
                    <div class="text-center">
                        <h1 class="display-1" style="color:red">No Projects Found</h1>
                    </div>
                </div>
            }

        </div>
    </div>
</div>